# Generated by Django 5.1.5 on 2025-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_prerequisite_subject_slug_alter_subject_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, choices=[('math', 'Basic Mathematics'), ('physics', 'Introduction to Physics'), ('chemistry', 'Basic Chemistry'), ('english', 'English Language')], to='subjects.prerequisite'),
        ),
    ]
