# Generated by Django 5.1.5 on 2025-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='name',
            field=models.CharField(choices=[('math', 'Basic Mathematics'), ('physics', 'Introduction to Physics'), ('chemistry', 'Basic Chemistry'), ('english', 'English Language')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='subjects.prerequisite'),
        ),
    ]
