# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_prerequisite_name_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prerequisites',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(blank=True, choices=[('math', 'Basic Mathematics'), ('physics', 'Introduction to Physics'), ('chemistry', 'Basic Chemistry'), ('english', 'English Language')], max_length=255),
        ),
    ]
