# Generated by Django 5.1.5 on 2025-02-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], default='ac', max_length=2),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
